services:
  galah:
    build: .
    container_name: galah
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
      - "8888:8888"
    environment:
      LLM_PROVIDER: "ollama"
      LLM_SERVER_URL: "http://ollama.local:11434"
      LLM_MODEL: "gemma2"
      # LLM_TEMPERATURE: "1"
      # LLM_API_KEY: "sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      # LLM_CLOUD_LOCATION: ""
      # LLM_CLOUD_PROJECT: ""
    volumes:
      - ./config/config.yaml:/galah/config/config.yaml
      - ./config/cert/:/galah/config/cert/
